name: Pyre Analyze

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Pyre
        run: |
          python -m pip install --upgrade pip
          pip install pyre-check
      - name: Install Project Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi          
      - name: Analyze with Pyre
        run: |
          pyre analyze --no-verify --save-results-to ./
      - name: Upload Artifact
        uses: fjogeleit/http-request-action@master
        with:
          url: http://full-loop-privacy-env.eba-tdfjxbhp.us-west-2.elasticbeanstalk.com/scans/upload
          method: 'POST'
          data: '{ "secret": "FLPFLP", "productID": 9, "source": "pyre", "codeUrl": "${{ github.server_url }}/${{ github.repository }}" }'
          files: '{ "file": "${{ github.workspace }}/taint-output.json" }'